[server]
port = 8501
address = "127.0.0.1"
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
serverAddress = "127.0.0.1"
serverPort = 8501
gatherUsageStats = false
